//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyBenhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_DONTHUOC
    {
        public string MA_DONTHUOC { get; set; }
        public string MA_THUOC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public decimal GIA_LUC_BAN { get; set; }
    
        public virtual DONTHUOC DONTHUOC { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
