//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyBenhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONTHUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONTHUOC()
        {
            this.CHITIET_DONTHUOC = new HashSet<CHITIET_DONTHUOC>();
        }
    
        public string MA_DONTHUOC { get; set; }
        public string MA_PHIEUKHAM { get; set; }
        public string MANV_KE { get; set; }
        public string MANV_XUAT { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYXUAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_DONTHUOC> CHITIET_DONTHUOC { get; set; }
        public virtual PHIEUKHAM PHIEUKHAM { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
    }
}
