//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyBenhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MA_HOADON { get; set; }
        public string MA_PHIEUKHAM { get; set; }
        public string MANV { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual PHIEUKHAM PHIEUKHAM { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
