//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyBenhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUKHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUKHAM()
        {
            this.DONTHUOCs = new HashSet<DONTHUOC>();
            this.HOADONs = new HashSet<HOADON>();
            this.PHIEUKHAM_DICHVU = new HashSet<PHIEUKHAM_DICHVU>();
        }
    
        public string MA_PHIEUKHAM { get; set; }
        public string MA_BENHNHAN { get; set; }
        public string MANV { get; set; }
        public Nullable<System.DateTime> NGAYKHAM { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONTHUOC> DONTHUOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUKHAM_DICHVU> PHIEUKHAM_DICHVU { get; set; }
    }
}
