//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyBenhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUKHAM_DICHVU
    {
        public string MA_PHIEUKHAM { get; set; }
        public string MA_DICHVU { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public decimal GIA_LUC_DUNG { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHIEUKHAM PHIEUKHAM { get; set; }
    }
}
