CREATE DATABASE QL_PHONG_KHAM
GO
USE QL_PHONG_KHAM
GO

-- =========================
-- 1. NHÂN SỰ
-- =========================
CREATE TABLE CHUYENKHOA (
    MaCK VARCHAR(15) PRIMARY KEY,
    TenCHUYENKHOA NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(15) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    ChucVu NVARCHAR(50) NOT NULL CHECK (ChucVu IN (N'Bác sĩ', N'Dược sĩ', N'Lễ tân', N'Thu ngân')),
    MaCK VARCHAR(15) NULL,
    CONSTRAINT FK_NV_CK FOREIGN KEY (MaCK) REFERENCES CHUYENKHOA(MaCK),
    CONSTRAINT CK_BACSI CHECK (ChucVu != N'Bác sĩ' OR MaCK IS NOT NULL)
);
GO
CREATE TABLE QUYEN (
    MaQuyen VARCHAR(10) PRIMARY KEY,
    TenQuyen NVARCHAR(50) NOT NULL -- 'Admin', 'User'
);
GO
CREATE TABLE TAIKHOAN (
    TenDangNhap VARCHAR(50) PRIMARY KEY,
    MatKhau VARCHAR(255) NOT NULL, 
    MaNV VARCHAR(15) UNIQUE,       
    MaQuyen VARCHAR(10),           -- Khóa ngoại tới bảng QUYEN
    TrangThai NVARCHAR(20) DEFAULT N'Hoạt động',
    CONSTRAINT FK_TK_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE CASCADE,
    CONSTRAINT FK_TK_QUYEN FOREIGN KEY (MaQuyen) REFERENCES QUYEN(MaQuyen)
);
GO
-- =========================
-- 2. DANH MỤC
-- =========================

CREATE TABLE BENHNHAN (
    MA_BENHNHAN NCHAR(5) PRIMARY KEY,
    TEN_BENHNHAN NVARCHAR(100),
    NGAYSINH DATE,
    GIOITINH NVARCHAR(10)
);
GO

CREATE TABLE DICHVU (
    MA_DICHVU NCHAR(5) PRIMARY KEY,
    TEN_DICHVU NVARCHAR(100),
    GIA_DV MONEY NOT NULL
);
GO

CREATE TABLE THUOC (
    MA_THUOC NCHAR(5) PRIMARY KEY,
    TEN_THUOC NVARCHAR(100),
    GIA_BAN MONEY NOT NULL,
    SOLUONG_TON INT DEFAULT 0 CHECK (SOLUONG_TON >= 0)
);
GO

-- =========================
-- 3. NGHIỆP VỤ
-- =========================

CREATE TABLE PHIEUKHAM (
    MA_PHIEUKHAM NCHAR(6) PRIMARY KEY,
    MA_BENHNHAN NCHAR(5),
    MANV VARCHAR(15),
    NGAYKHAM DATETIME DEFAULT GETDATE(),
    TRANGTHAI NVARCHAR(30) DEFAULT N'Đang khám',
    FOREIGN KEY (MA_BENHNHAN) REFERENCES BENHNHAN(MA_BENHNHAN),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MaNV)
);
GO

-- SNAPSHOT GIÁ DỊCH VỤ
CREATE TABLE PHIEUKHAM_DICHVU (
    MA_PHIEUKHAM NCHAR(6),
    MA_DICHVU NCHAR(5),
    SOLUONG INT DEFAULT 1,
    GIA_LUC_DUNG MONEY NOT NULL, -- FIX QUAN TRỌNG
    PRIMARY KEY (MA_PHIEUKHAM, MA_DICHVU),
    FOREIGN KEY (MA_PHIEUKHAM) REFERENCES PHIEUKHAM(MA_PHIEUKHAM) ON DELETE CASCADE,
    FOREIGN KEY (MA_DICHVU) REFERENCES DICHVU(MA_DICHVU)
);
GO

CREATE TABLE DONTHUOC (
    MA_DONTHUOC NCHAR(6) PRIMARY KEY,
    MA_PHIEUKHAM NCHAR(6),
    MANV_KE VARCHAR(15),
    MANV_XUAT VARCHAR(15) NULL,
    TRANGTHAI NVARCHAR(30) DEFAULT N'Chờ xuất'
        CHECK (TRANGTHAI IN (N'Chờ xuất', N'Đã xuất', N'Đã huỷ')),
    NGAYXUAT DATETIME NULL,
    FOREIGN KEY (MA_PHIEUKHAM) REFERENCES PHIEUKHAM(MA_PHIEUKHAM),
    FOREIGN KEY (MANV_KE) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MANV_XUAT) REFERENCES NHANVIEN(MaNV),

    CONSTRAINT CK_XUAT_THUOC CHECK (
        TRANGTHAI != N'Đã xuất'
        OR (MANV_XUAT IS NOT NULL AND NGAYXUAT IS NOT NULL)
    )
);
GO

-- SNAPSHOT GIÁ THUỐC
CREATE TABLE CHITIET_DONTHUOC (
    MA_DONTHUOC NCHAR(6),
    MA_THUOC NCHAR(5),
    SOLUONG INT CHECK (SOLUONG > 0),
    GIA_LUC_BAN MONEY NOT NULL, -- FIX QUAN TRỌNG
    PRIMARY KEY (MA_DONTHUOC, MA_THUOC),
    FOREIGN KEY (MA_DONTHUOC) REFERENCES DONTHUOC(MA_DONTHUOC) ON DELETE CASCADE,
    FOREIGN KEY (MA_THUOC) REFERENCES THUOC(MA_THUOC)
);
GO

CREATE TABLE HOADON (
    MA_HOADON NCHAR(6) PRIMARY KEY,
    MA_PHIEUKHAM NCHAR(6),
    MANV VARCHAR(15),
    TONGTIEN MONEY DEFAULT 0,
    TRANGTHAI NVARCHAR(30) DEFAULT N'Chưa thanh toán',
    FOREIGN KEY (MA_PHIEUKHAM) REFERENCES PHIEUKHAM(MA_PHIEUKHAM),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MaNV)
);
GO  -- <==== QUAN TRỌNG: CHỮ GO NÀY GIẢI QUYẾT TẤT CẢ CÁC LỖI Ở TRÊN

-- =========================
-- 4. TRIGGER TÍNH TIỀN (ĐÚNG CHỖ)
-- =========================

CREATE TRIGGER trg_UpdateTongTien_DV
ON PHIEUKHAM_DICHVU
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    UPDATE HD
    SET TONGTIEN =
        ISNULL((
            SELECT SUM(SOLUONG * GIA_LUC_DUNG)
            FROM PHIEUKHAM_DICHVU
            WHERE MA_PHIEUKHAM = HD.MA_PHIEUKHAM
        ),0)
        +
        ISNULL((
            SELECT SUM(CT.SOLUONG * CT.GIA_LUC_BAN)
            FROM DONTHUOC DT
            JOIN CHITIET_DONTHUOC CT ON DT.MA_DONTHUOC = CT.MA_DONTHUOC
            WHERE DT.MA_PHIEUKHAM = HD.MA_PHIEUKHAM
            AND DT.TRANGTHAI = N'Đã xuất'
        ),0)
    FROM HOADON HD
END
GO

CREATE TRIGGER trg_UpdateTongTien_Thuoc
ON CHITIET_DONTHUOC
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    UPDATE HD
    SET TONGTIEN =
        ISNULL((
            SELECT SUM(SOLUONG * GIA_LUC_DUNG)
            FROM PHIEUKHAM_DICHVU
            WHERE MA_PHIEUKHAM = HD.MA_PHIEUKHAM
        ),0)
        +
        ISNULL((
            SELECT SUM(CT.SOLUONG * CT.GIA_LUC_BAN)
            FROM DONTHUOC DT
            JOIN CHITIET_DONTHUOC CT ON DT.MA_DONTHUOC = CT.MA_DONTHUOC
            WHERE DT.MA_PHIEUKHAM = HD.MA_PHIEUKHAM
            AND DT.TRANGTHAI = N'Đã xuất'
        ),0)
    FROM HOADON HD
END
GO

-- =========================
-- 5. TRIGGER TRỪ KHO
-- =========================

CREATE TRIGGER trg_TruKho
ON DONTHUOC
AFTER UPDATE
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM inserted i
        JOIN deleted d ON i.MA_DONTHUOC = d.MA_DONTHUOC
        WHERE i.TRANGTHAI = N'Đã xuất' AND d.TRANGTHAI != N'Đã xuất'
    ) RETURN;

    UPDATE T
    SET SOLUONG_TON = SOLUONG_TON - CT.SOLUONG
    FROM THUOC T
    JOIN CHITIET_DONTHUOC CT ON T.MA_THUOC = CT.MA_THUOC
    JOIN inserted I ON CT.MA_DONTHUOC = I.MA_DONTHUOC;

    IF EXISTS (SELECT 1 FROM THUOC WHERE SOLUONG_TON < 0)
    BEGIN
        RAISERROR(N'Không đủ thuốc',16,1);
        ROLLBACK TRANSACTION;
    END
END
GO